### ISSUE TITLE
Nie znikające pociski

### ISSUE THREAD

**Issue by p4szczak** [Sevdariel/Tower_defense#2]
![image](https://user-images.githubusercontent.com/31289769/30060546-23e51450-9244-11e7-9902-6d645f2d829d.png)

Jeżeli postawimy wieżyczkę dokładnie w tym miejscu i dokładnie jedną to dla części przeciwników działa dobrze jednak przy ostatnim przeciwniku wyskakuje błąd.

**Comment by Sevdariel** [comment]
fixed arrow speed increased
